spring.application.name=airBnb

#DB configuration
spring.datasource.url=jdbc:postgresql://dpg-d9k8052jobas7387gl40-a/airbnb_db_zqed
spring.datasource.username=airbnb_db_zqed_user
spring.datasource.password=yWCe5uUU3j4HsHwISaAmPHYb3r14dia0
spring.jpa.hibernate.ddl-auto=update



server.servlet.context-path=/api/v1

jwt.secretKey=hdgyq37t46726udfuywr89723hfbkuy4389ryuhqbguyt98347rfhuht74982yrghhty47y84uhfbu4yr7824

frontend.url=http://localhost:8080

razorpay.key.id=rzp_test_T94lZtE821djyw
razorpay.key.secret=XtT6wyJEnxEUYV1itNs7RPuS

razorpay.webhook.secret=mywebhook2701

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect