spring.application.name=airBnb

# Server configuration
server.port=${PORT:8080}
server.servlet.context-path=/api/v1

# DB configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:airBnb}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Sneha01}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security
jwt.secretKey=${JWT_SECRET_KEY:hdgyq37t46726udfuywr89723hfbkuy4389ryuhqbguyt98347rfhuht74982yrghhty47y84uhfbu4yr7824}

# Frontend Client URL
frontend.url=${FRONTEND_URL:http://localhost:8080}

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_T94lZtE821djyw}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:XtT6wyJEnxEUYV1itNs7RPuS}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:mywebhook2701}