spring.application.name=airBnb

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.datasource.username=postgres
spring.datasource.password=Sneha01
spring.jpa.hibernate.ddl-auto=update



server.servlet.context-path=/api/v1

jwt.secretKey=hdgyq37t46726udfuywr89723hfbkuy4389ryuhqbguyt98347rfhuht74982yrghhty47y84uhfbu4yr7824

frontend.url=http://localhost:8080

razorpay.key.id=rzp_test_T94lZtE821djyw
razorpay.key.secret=XtT6wyJEnxEUYV1itNs7RPuS

razorpay.webhook.secret=mywebhook2701

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect